#!/usr/bin/env python3
"""Assemble hex2.hex1 from hex2_helper.py output.
Reorders sections, adds hex1 labels, generates PE header, adds padding.

This is the *outer* assembler that wraps the per-function
instruction blocks emitted by hex2_helper.py. The helper outputs
each function's body independently; this script:
  * Invokes hex2_helper.py and captures its stdout.
  * Parses out section markers / function names from the output.
  * Re-orders sections so the entry function lands at offset 0x240
    (right after the PE32+ header), with subsequent functions
    placed in dependency order.
  * Inserts hex1 `:label` markers at function entry points and
    `%label` references at call sites so the hex1 linker can
    resolve cross-function jumps.
  * Prepends a hand-rolled PE32+ COFF header (Machine = 0x5064 for
    RV64) with placeholder size fields that hex1 patches at link
    time via `[PATCH]` markers.
  * Pads .text to a 64-byte boundary (PE FileAlignment) so the
    section table's PointerToRawData / SizeOfRawData stay valid.

Run this any time hex2_helper.py changes, then paste the output
into riscv64/hex2.hex1.
"""
import re, math, struct, subprocess, sys

# Generate hex2 body
result = subprocess.run([sys.executable, 'Development/riscv64/hex2_helper.py'],
                       capture_output=True, text=True)
if result.returncode != 0:
    print(result.stderr, file=sys.stderr)
    sys.exit(1)
content = result.stdout

# Parse into sections
sections = {}
cn = None; cl = []
for line in content.split('\n'):
    if line.startswith('# === ') and line.endswith(' ==='):
        if cn: sections[cn] = '\n'.join(cl)
        cn = line; cl = [line]
    else:
        cl.append(line)
if cn: sections[cn] = '\n'.join(cl)

# Reorder: _start first, data last
order = ['# === _start (at 0x240) ===']
order += [k for k in sections if k not in ('# === _start (at 0x240) ===', '# === Data section ===')]
order += ['# === Data section ===']
body = '\n\n'.join(sections[n] for n in order if n in sections)

# Add hex1 labels before each function
label_map = {
    '# === Read_byte (:x) ===': ':x',
    '# === write_out (:z) ===': ':z',
    '# === hex (:l) ===': ':l',
    '# === consume_token (:A) ===': ':A',
    '# === ClearScratch (:H) ===': ':H',
    '# === StoreLabel (:C) ===': ':C',
    '# === GetTarget (:D) ===': ':D',
    '# === StorePointer (:K) ===': ':K',
    '# === First_pass (:c) ===': ':c',
    '# === Second_pass (:m, loop at :n) ===': ':m',
    '# === StorePointer_rel4 (:M) ===': ':M',
    '# === StorePointer_abs4 (:N) ===': ':N',
    '# === encode_U (~) (:P) ===': ':P',
    '# === encode_I (!) (:Q) ===': ':Q',
    '# === encode_B (@) (:W) ===': ':W',
    '# === encode_J ($) (:9) ===': ':9',
    '# === dot_load (:O) ===': ':O',
    '# === fail (:R) ===': ':R',
    '# === Done (:S) ===': ':S',
    '# === terminate (:T) ===': ':T',
}
for header, label in label_map.items():
    body = body.replace(header, header + '\n' + label)

# Add :n label at Second_pass loop head (after frame push, at the :loop comment)
# Find the :loop WITHIN Second_pass section (not First_pass)
sp2_marker = '# === Second_pass (:m, loop at :n) ==='
sp2_idx = body.find(sp2_marker)
if sp2_idx >= 0:
    loop_in_sp2 = body.find('# [0x0008] :loop\n', sp2_idx)
    if loop_in_sp2 >= 0:
        body = body[:loop_in_sp2] + '# [0x0008] :loop\n:n\n' + body[loop_in_sp2 + len('# [0x0008] :loop\n'):]

# Count code bytes
total = 0
for line in body.split('\n'):
    line = line.strip()
    if not line or line.startswith('#') or line.startswith(':'):
        continue
    code = line.split(';')[0].strip()
    if not code:
        continue
    for p in code.split():
        if p.startswith('%'):
            total += 4
        elif re.match(r'^[0-9A-Fa-f]{2}$', p):
            total += 1

raw = int(math.ceil(total / 0x40)) * 0x40
img = 0x240 + raw
pad = raw - total

def le32(v):
    return ' '.join(f'{b:02X}' for b in struct.pack('<I', v))

# PE header
header = f"""# hex2 linker for RISC-V 64-bit UEFI - generated by hex2_helper.py
4D 5A 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 80 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
50 45 00 00
64 50
01 00
00 00 00 00 00 00 00 00 00 00 00 00
F0 00
2E 00
0B 02 00 00
{le32(total)}
00 00 00 00
00 00 00 00
40 02 00 00
40 02 00 00
00 00 00 00 00 00 00 00
40 00 00 00
40 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
{le32(img)}
40 02 00 00
00 00 00 00
0A 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00
10 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2E 74 65 78 74 00 00 00
{le32(total)}
40 02 00 00
{le32(raw)}
40 02 00 00
00 00 00 00 00 00 00 00 00 00 00 00
20 00 00 60
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
"""

# Write output
output_path = 'riscv64/hex2.hex1'
with open(output_path, 'w') as f:
    f.write(header)
    f.write(body)
    if pad > 0:
        f.write('\n# Padding\n')
        remaining = pad
        while remaining >= 16:
            f.write('00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00\n')
            remaining -= 16
        while remaining > 0:
            f.write('00 ')
            remaining -= 1
        f.write('\n')

print(f'Generated {output_path}: code=0x{total:X}, raw=0x{raw:X}, img=0x{img:X}, pad={pad}')
